config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/params_check'
  root 'welcome#index'

  resources :articles 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	validates :title, presence: true
	validates :text, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
	end

	def create
		@article = Article.new(require_params params) 
		if @article.save
			redirect_to @article
		else
			puts "error when saving article"
			redirect_to new_article_path

		end		
	end

	def show
		puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
		@article = Article.find params[:id]
		if @article.nil?
			render json: {error: "Article not found"}
		end
		p @article
		puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	end	

	def index
		@articles = Article.all
		p @articles
	end

	private
		def require_params parameters
			parameters.require(:article).permit(:title, :text)
		end
end	

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def params_check
  	puts "*** printing parameters"
  	p params
  	puts "*** printing parameters"

  	puts "*** printing request"
  	p request
  	puts "*** printing request"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<%= link_to 'Write a New article', new_article_path %>

<% @articles.each do |article| %>
	<h3> <%= article.title %> </h3>
	<textarea rows="4" cols="50"> <%= article.text %> </textarea>
	<%= link_to 'Blog', article %>
<% end %>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Read all articles', articles_path %>

app/views/articles/show.html.erb
<h1> <b><%= @article.title %> </b></h1>
<br> 
<p> <i><%= @article.text %></i></p>

<%= link_to 'Read all articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>"Hello Rails"</h1>

app/views/welcome/params_check.html.erb
<h1>Checking Parameters passed</h1>